
script:
  - rm -R test Server README.md
  - mkdir ../pages
  - mv Front-end/* ../pages
  # - rm -R Front-end
  # - echo "bufsm.dalmago.xyz" > ../pages/CNAME

after_success:
    - cd ../pages
    - git init
    - git config --local user.name ${MY_NAME}
    - git config --local user.email ${MY_EMAIL}
    - git add .
    - git commit -m "Automatically deploying to gh-pages"
    - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/dalmago/bufsm.git" master:gh-pages

branches:
  only:
  - master

notifications:
  slack: bufsm:lxRX5FKHZuhyQi9UftbsXUuk
