
script:
  - rm -R test Server README.md
  - mkdir ../pages
  - mv Front-end/* ../pages
  # - rm -R Front-end
  # - echo "bufsm.dalmago.xyz" > ../pages/CNAME

after_success:
    - cd ../pages
    - git init
    - git config --local user.name ${MY_NAME}
    - git config --local user.email ${MY_EMAIL}
    - git add .
    - git commit -m "Automatically deploying to gh-pages"
    - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/dalmago/bufsm.git" master:gh-pages

branches:
  only:
  - master

notifications:
  slack: secure: VM2wzV7LZ650AP2y4YrVZmvJc9hfGXaxOs5O+fsI7oOmHD07M1K6KNAes+XutHZmTOaQ1xYjYvowK3/mzFqOkM4dPIj2rnDSGQ8C9uQZfz4xMl/85k4pU+h3z9tJ0yQ0/fKA7fG7OADVazW+lQYETd8xCgQwqf8X3zAMrgryDnaj+CWnzTNL3sr7rCD5Uk5wW9NJEe0ZQHwrG7B16FV/up6jpzJmbN5+khlXmhg82MBus+o82C+zM9ikJFLTXijr/KdhyQZcBHZTD89QwvOvT6kxQy63CMXQcwyJSzLG+Hh6RNNB2qVxP+/cRB/lN1oY00XGmX/Vz+b8e/SDFdFZeGY/qKu4Chbuf1wdT+sfHItll3wbVXwbcIafDHD3LIxD2WbgJP8TE3QjltbgQ/n4XlVfOV0BZtvDFGbgFL8O9ehZVe9TnzQ82IVMc3JK5mAKqMbkuMpUdtOA/Nu2V/ZQpUSnbkflwR28v4Ra+lDiGJe5jpYS5Is1dOf4e3zLPPjxbgTrWvNREXnHqEyV1djXbqMUQ2SPSb0n2O97ojM0wCk8qhdVZiFX372TcrvItf2q6OwE3aPLanqM0uG4mnNn1eMzwMcnSU0RcED93WOzR/jglQT6wkRBjqZn3V+EA9XX3ESjLMVsb5wp2fnW64ImDGGwGnWWM7IKGePc9vDlyM8=
