
script:
  - rm -R test Server README.md
  - mkdir ../pages
  - mv Front-end/* ../pages
  - echo bufsm.dalmago.xyz > ../pages/CNAME
  # - rm -R Front-end
  # - echo "bufsm.dalmago.xyz" > ../pages/CNAME

after_success:
    - cd ../pages
    - git init
    - git config --local user.name ${MY_NAME}
    - git config --local user.email ${MY_EMAIL}
    - git add .
    - git commit -m "Automatically deploying to gh-pages"
    - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/dalmago/bufsm.git" master:gh-pages

branches:
  only:
  - master

notifications:
  slack:
    secure: SIZBlgmDVL8KbaeR3YN4AVI8wI7QFLoFsaEAH2I1leNsc8DvnS2F5LYnW+wpVSbcWyLX3uCvTFGAaygP/QE7t63+Q1EjQ5hrovIWiIKR0v1xIRPyYhWhmX1ZbQNCOdXAFshw6QCR/vmgbS5Y07JTWSIx6BWpQbuv8RMgf8jfKiX7Bn8jL42aE2GWcQA3B9LWVfujF74ruUCN+Ppmy/B3ES1M1yOoD1txHXF+qDk6WxylXyrJeAAuJrOud4vaYkWEbzA2l9ITQ9jIcu4APLBDE2YCdLFwqRx3rsL6Tx7WszeC4lCIKlJ/PdEc736xuhm89HwtI8anyN2z42fIl3mGrAXhYkEYeWQp9Y3772mjjeTgF4a41GkLzKWsYIiWdJR/ivKHNhk+YzXGgnf5NOlril1zdDK9KieuRuMkY7ulveXjLKcEX/WCzh3AugdvjZpguGLgt8VoaeQE/i17ELlT+Yjw9RUtBmyWEYSb205ZxEorMaVLEeHfHWlzcHcT90iIwY2kragBQGic6Yf1DlSK/mHP7fNNKgyBZfqHK1oEHh32y7KrSux7FBBPZFcBO6P06X/fdWuwBVwbhqh/uFS/mZtiOnTu3x85Q7uSIk/ZGoyCUT8LXP0x7cWzL1WB9CvyM64QzUDlvhzrO919pB8dWI9drS8XXvIE40yIQLZ0qKw=
