
script:
  - mkdir ../pages
  - mv front-end/* ../pages

after_success:
    - cd ../pages
    - git init
    - git config --local user.name ${MY_NAME}
    - git config --local user.email ${MY_EMAIL}
    - git add .
    - git commit -m "Automatically deploying to gh-pages"
    - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/bufsm/bufsm.github.io.git" master:master

branches:
  only:
  - master
